### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by nafetsrybak** [nafetsrybak/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Povkhanych-Rybak** [comment]
“I’m the most successful person ever to run for the presidency, by far,” he told Des Moines Register this month. “Nobody’s ever been more successful than me. I’m the most successful person ever to run. Ross Perot isn’t successful like me. Romney – I have a Gucci store that’s worth more than Romney.”

**Comment by nafetsrybak** [comment]
Thanks a lot!
