### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by nafetsrybak** [nafetsrybak/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Povkhanych-Rybak** [comment]
**DONALD TRUMP**

- https://www.facebook.com/DonaldTrump

- realDonaldTrump@whitehouse.gov

- https://twitter.com/realdonaldtrump

- https://www.instagram.com/realdonaldtrump/

**Comment by nafetsrybak** [comment]
Thanks a lot!
