### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by nafetsrybak** [nafetsrybak/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Povkhanych-Rybak** [comment]
**Chairman and president, The Trump Organization, 1971–present:**

- “The Trump Organization is the world’s only global luxury real estate super-brand”

- Oversees 22,000 employees

- Responsible for Trump-branded residences, offices and hotels across US

- Owns golf courses, battled with residents over opening of a course in Aberdeenshire, Scotland

**Host, The Apprentice, The Celebrity Apprentice, 2004–present:**

- Hired and fired a number of business hopefuls

- Believed some female contestants were after more than just a job: “All of the women on The 

- Apprentice flirted with me — consciously or unconsciously. That’s to be expected.”

**Chapter 11 bankruptcy filer, 1991–?:**

- Filed on four separate occasions: “I’ve used the laws of this country to pare debt. … We’ll have the company. We’ll throw it into a chapter. We’ll negotiate with the banks. We’ll make a fantastic deal. You know, it’s like on The Apprentice. It’s not personal. It’s just business.”

**Writer, 1987–present:**

- Trump: The Art of the Deal

- Trump: The Art of Survival

- Trump: The Art of the Comeback

- Trump: The Best Golf Advice I Ever Received

**Owner, founder, Trump University, 2005–2010; Trump Entrepreneur Initiative founder, owner, 2010–present:**

- Said Trump University was “Ivy League-quality”; students disagreed: “Trump, as far as I can tell, had no real involvement in this program at all, other than collecting money, obviously. The thing’s a joke.”

- New York attorney general brought lawsuit against Trump University in 2013. From the New York Times: “At one seminar, participants were told they would get to have their pictures taken with Mr Trump; it ended up being with a cardboard cutout.”

- Changed name of “school” after New York Education Department said the use of the word “university” was “misleading” and “violates” state law

**Founder, Trump Entertainment Resorts, 1995–2009:**

- Owned hotels and casinos including the Trump Taj Mahal in Atlantic City, which was under threat of closure in 2014. Trump Entertainment Resorts also owned the Trump Plaza casino, which closed in 2014.

**Comment by nafetsrybak** [comment]
Thanks a lot!
